name: gym_ubb_server
description: GymUBB — Backend API (Dart + Shelf)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # HTTP server
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # Base de datos
  postgres: ^3.3.0

  # Cache / blacklist tokens
  redis: ^3.1.0

  # Autenticación
  dart_jsonwebtoken: ^2.12.2
  bcrypt: ^1.1.3

  # Utilities
  uuid: ^4.4.0

  # Email (verificación de registro)
  mailer: ^6.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
